### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by canyie** [canyie/canyie.github.io#3]
EMG：
- [x] 计算机二级，不过过不过，报了就不能浪费我的小钱钱（
- [x] CSP
- [x] 高考

成年后：
- [x] 填器官捐献志愿

高考完：
- [ ] Dreamland and Pine
- [ ] Magisk Bravo!
- [ ] 看完药空 (2022/8/18 本书已被原小说网站下架 百度网盘封杀分享)
- [x] something bad but i needed

**Comment by Errant404** [comment]
加油呀！

**Comment by QINGChuzhe** [comment]
**_Canyie_** 哥哥好NB[滑稽]

**Comment by NgaiYeanCoi** [comment]
该设定新的todolist了

**Comment by canyie** [comment]
> 该设定新的todolist了

你怎么还跑过来监控我

**Comment by NgaiYeanCoi** [comment]
> > 该设定新的todolist了
> 
> 你怎么还跑过来监控我

啊这
